---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: incident-reporting-ui-build-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/tompscanlan/incident-reporting
---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: incident-reporting-ui-build-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/tompscanlan/incident-reporting-ui
---
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
---
apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-incident-reporting-ui-from-git-task-run
spec:
  taskRef:
    name: build-docker-image-from-git-source
  trigger:
    type: manual
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: incident-reporting-ui-build-git
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/docker-source/ui-server
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: incident-reporting-ui-build-image