# must run
# kubectl create secret docker-registry harborregistrykey --docker-server=harbor-harbor-portal.default.svc.cluster.local --docker-username=admin --docker-password=Harbor12345 --docker-email=tompscanlan@gmail.com

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: harbor-watcher
    release: v1
  name: harbor-watcher
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harbor-watcher
      release: v1
  template:
    metadata:
      labels:
        app: harbor-watcher
        release: v1
    spec:
      imagePullSecrets:
        - name:  harborregistrykey
      containers:
      - image: harbor.demo.butterhead.net/library/monitor:latest
        name: harbor-watcher
        resources:
          limits:
            cpu: 200m
            memory: 128M
          requests:
            cpu: 100m
            memory: 32M
      restartPolicy: Always
---
# requires cert-manager to be installed
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: tscanlan@vmware.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: tscanlan@vmware.com
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory